// ==================== 马恩选集 ====================
window.readingData["马恩选集"] = [
    // 第一卷 1843-1859年
    { id: 1, title: "黑格尔法哲学批判导言", link: "../1-黑格尔法哲学批判导言", author: "卡·马克思", status: "思考观后感中", startDate: "2026.4.13", endDate: "2026.4.20", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 2, title: "国民经济学批判大纲", link: "../2-国民经济学批判大纲", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 3, title: "1844年经济学哲学手稿", link: "../3-1844年经济学哲学手稿", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 4, title: "英国工人阶级状况", link: "../4-英国工人阶级状况", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 5, title: "关于费尔巴哈的提纲", link: "../5-关于费尔巴哈的提纲", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 6, title: "德意志意识形态", link: "../6-德意志意识形态", author: "马、恩", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 7, title: "哲学的贫困", link: "../7-哲学的贫困", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 8, title: "共产主义者和卡尔·海因岑", link: "../8-共产主义者和卡尔·海因岑", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 9, title: "共产主义原理", link: "../9-共产主义原理", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 10, title: "关于波兰的演说", link: "../10-关于波兰的演说", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 11, title: "雇佣劳动与资本", link: "../11-雇佣劳动与资本", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 12, title: "关于自由贸易问题的演说", link: "../12-关于自由贸易问题的演说", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 13, title: "共产党宣言", link: "../13-共产党宣言", author: "马、恩", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 14, title: "危机与反革命", link: "../14-危机与反革命", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 15, title: "资产阶级与反革命", link: "../15-资产阶级与反革命", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 16, title: "1848年至1850年的法兰西阶级斗争", link: "../16-1848年至1850年的法兰西阶级斗争", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 17, title: "共产主义者同盟中央委员会告同盟书", link: "../17-共产主义者同盟中央委员会告同盟书", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 18, title: "德国的革命与反革命", link: "../18-德国的革命与反革命", author: "弗·恩格斯", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 19, title: "路易·波拿巴的雾月十八日", link: "../19-路易·波拿巴的雾月十八日", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 20, title: "在人民报创刊纪念会上的演说", link: "../20-在人民报创刊纪念会上的演说", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 21, title: "中国革命与欧洲革命", link: "../21-中国革命与欧洲革命", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 22, title: "俄国的对华贸易", link: "../22-俄国的对华贸易", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 23, title: "英人在华的残暴行动", link: "../23-英人在华的残暴行动", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 24, title: "波斯和中国", link: "../24-波斯和中国", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 25, title: "鸦片贸易史", link: "../25-鸦片贸易史", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 26, title: "英中条约", link: "../26-英中条约", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 27, title: "中国和英国的条约", link: "../27-中国和英国的条约", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 28, title: "俄国在远东的成功", link: "../28-俄国在远东的成功", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 29, title: "新的对华战争", link: "../29-新的对华战争", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 30, title: "对华贸易", link: "../30-对华贸易", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 31, title: "不列颠在印度的统治", link: "../31-不列颠在印度的统治", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" },
    { id: 32, title: "不列颠在印度统治的未来结果", link: "../32-不列颠在印度统治的未来结果", author: "卡·马克思", status: "未开始", startDate: "", endDate: "", rating: null, notes: "", volume: "第一卷 1843-1859年" }
];